{
 "title": "Dero Node Statistics",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Network Difficulty",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "derod_difficulty" }
   ]
  },
  {
   "title": "Blocks Accepted/Rejected",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(derod_miniblocks_accepted_count) + sum(derod_blocks_count)"
    },
    {
     "expr": "derod_miniblocks_rejected_count"
    },
    { "expr": "derod_hashrate_1hr" },
    { "expr": "derod_hashrate_1d" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "derod_peer_count" },
    { "expr": "derod_peer_whitelist" }
   ]
  },
  {
   "title": "Miniblocks in Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "derod_miniblocks_in_memory" }
   ]
  },
  {
   "title": "Peer Latency(ms)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "derod_peer_latency" }
   ]
  },
  {
   "title": "Block Height Delta",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "derod_height_delta" }
   ]
  },
  {
   "title": "TX in Mempool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "derod_tx_pool_size" }
   ]
  },
  {
   "title": "Registration TX in Regpool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "derod_reg_pool_size" }
   ]
  },
  {
   "title": "Inbound/Outbound Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "derod_incoming_connections_count"
    },
    {
     "expr": "derod_outgoing_connections_count"
    }
   ]
  },
  {
   "title": "Number of Miners",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "derod_connected_miners" }
   ]
  }
 ]
}